CREATE OR REPLACE TRIGGER TRGCORRIGIRALTERACAOBONUS
    AFTER UPDATE
    ON CAMAREIRA
    FOR EACH ROW
DECLARE
    E_MENOR EXCEPTION;
    E_AUMENTO EXCEPTION;
BEGIN
    IF :NEW.BONUS < :OLD.BONUS THEN
        RAISE E_MENOR;
    ELSIF :NEW.BONUS > :OLD.BONUS * 1.5 THEN
        RAISE E_AUMENTO;
    END IF;
EXCEPTION
    WHEN E_MENOR THEN
        RAISE_APPLICATION_ERROR(-20005, 'NAO PODE DIMINUIR O BONUS DE UMA CAMAREIRA');
    WHEN E_AUMENTO THEN
        RAISE_APPLICATION_ERROR(-20005, 'NAO PODE OFERECER UM AUMENTO SUPERIOR A 50% DO BONUS ATUAL DE UMA CAMAREIRA');
END;


-- TEST
-- CAMAREIRA COM BONUS = 11.05, NAO PODE ACEITAR INFERIOR
BEGIN
    -- UPDATE FALHA PORQUE NAO SE PODE REDUZIR AUMENTA
    UPDATE CAMAREIRA
    SET BONUS=1
    WHERE ID = 18;

    -- CAMAREIRA COM BONUS = 5.5€, PODE COLOCAR 8.25€ MAS NAO PODE COLOCAR 9€
    UPDATE CAMAREIRA
    SET BONUS=8.25
    WHERE ID = 13;
END;
