CREATE OR REPLACE TRIGGER TRGEPOCASNAOSOBREPOSTAS
    AFTER INSERT OR UPDATE
    ON EPOCA
DECLARE
    FLAG NUMBER;
BEGIN
    -- VAMOS COLOCAR NA FLAG A CONTAGEM DO NUMERO DE EPOCAS EM QUE SE VERIFICA A CONDICAO DE SOBREPOSICAO: A DATA A
    -- INSERIR SOBREPOEM QUALQUER PERIODO DAS EPOCAS JA EXISTENTES EM SISTEMA. O SELECT 1 SERVE APENAS PARA QUE SEJA
    -- SELECIONADO O NUMERO 1 CASO A CLAUSULA WHERE SE VERIFIQUE
    SELECT COUNT(*)
    INTO FLAG
    FROM EPOCA E
    WHERE EXISTS(SELECT 1
                 FROM EPOCA E2
                 WHERE (E.DATA_INI BETWEEN E2.DATA_INI AND E2.DATA_FIM OR E.DATA_FIM
                     BETWEEN E2.DATA_INI AND E2.DATA_FIM)
                   AND E2.ROWID <> E.ROWID);

    -- CASO A CONTAGEM SEJA MAIOR QUE 0 ENTAO SIGNIFICA QUE EXISTE SOBREPOSICAO DA DATA A INSERIR/MODIFICAR COM
    -- OUTRAS EPOCAS JA EXISTENTES
    IF FLAG > 0 THEN
        RAISE_APPLICATION_ERROR(-20021, 'INSERT FAILED BECAUSE SELECTED DATES OVERLAP EXISTENT ONES');
    END IF;
END;

-- TESTS
-- ALL OF THESE SHOULD FAIL
INSERT INTO EPOCA
VALUES (11, ' EPOCA 5 ', TO_DATE('2020-09-02', 'yyyy-mm-dd'), TO_DATE('2020-12-27', 'yyyy-mm-dd'));

UPDATE EPOCA
SET DATA_INI=TO_DATE('2020-09-05', 'yyyy-mm-dd'),
    DATA_FIM= TO_DATE('2020-12-10', 'yyyy-mm-dd')
WHERE ID = 3;
