--!!!! WARNING !!!!
--!!!! Eliminar TODAS as tabelas do schema !!!!
--!!!!

BEGIN
    FOR R IN (SELECT 'drop table ' || TABLE_NAME || ' cascade constraints' CMD FROM USER_TABLES ORDER BY TABLE_NAME)
        LOOP
            EXECUTE IMMEDIATE (R.CMD);
        END LOOP;
END;
/

CREATE TABLE PAIS
(
    ID   INT
        CONSTRAINT PK_PAIS PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE DISTRITO
(
    ID      INT
        CONSTRAINT PK_DISTRITO PRIMARY KEY,
    ID_PAIS INT
        CONSTRAINT FK_DISTRITO_PAIS REFERENCES PAIS (ID),
    NOME    VARCHAR(250)
);

CREATE TABLE CONCELHO
(
    ID          INT
        CONSTRAINT PK_CONCELHO PRIMARY KEY,
    ID_DISTRITO INT
        CONSTRAINT FK_CONCELHO_DISTRITO REFERENCES DISTRITO (ID),
    NOME        VARCHAR(250)
);

CREATE TABLE LOCALIDADE
(
    ID          INT
        CONSTRAINT PK_LOCALIDADE PRIMARY KEY,
    ID_CONCELHO INT
        CONSTRAINT FK_LOCALIDADE_CONCELHO REFERENCES CONCELHO (ID),
    NOME        VARCHAR(250)
);

CREATE TABLE CODIGO_POSTAL
(
    ID                INT
        CONSTRAINT PK_CODIGO_POSTAL PRIMARY KEY,
    ID_LOCALIDADE     INT
        CONSTRAINT FK_CODIGO_POSTAL_LOCALIDADE REFERENCES LOCALIDADE (ID),
    DESIGNACAO_POSTAL VARCHAR(250)
);

CREATE TABLE CLIENTE
(
    ID            INT
        CONSTRAINT PK_CLIENTE PRIMARY KEY,
    NOME          VARCHAR(250),
    NIF           VARCHAR(15) UNIQUE,
    ID_LOCALIDADE INT
        CONSTRAINT FK_CLIENTE_LOCALIDADE REFERENCES LOCALIDADE (ID),
    EMAIL         VARCHAR(200) UNIQUE,
    TELEFONE      VARCHAR(20)
);

CREATE TABLE ESTADO_RESERVA
(
    ID   INT
        CONSTRAINT PK_ESTADO_RESERVA PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE EPOCA
(
    ID       INT
        CONSTRAINT PK_EPOCA PRIMARY KEY,
    NOME     VARCHAR(250),
    DATA_INI DATE
        CONSTRAINT NN_EPOCA_DATA_INI NOT NULL,
    DATA_FIM DATE,
    CONSTRAINT CK_EPOCA_DATAS CHECK (DATA_INI < DATA_FIM)
);

CREATE TABLE ANDAR
(
    ID       INT
        CONSTRAINT PK_ANDAR PRIMARY KEY,
    NOME     VARCHAR(250),
    NR_ANDAR INT UNIQUE
);

CREATE TABLE TIPO_QUARTO
(
    ID   INT
        CONSTRAINT PK_TIPO_QUARTO PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE PRECO_EPOCA_TIPO_QUARTO
(
    ID_EPOCA       INT
        CONSTRAINT FK_PRECO_EPOCA_EPOCA REFERENCES EPOCA (ID),
    ID_TIPO_QUARTO INT
        CONSTRAINT FK_PRECO_EPOCA_TIPO REFERENCES TIPO_QUARTO (ID),
    CONSTRAINT PK_PRECO_EPOCA_TIPO_QUARTO PRIMARY KEY (ID_EPOCA, ID_TIPO_QUARTO),
    PRECO          NUMBER(6, 2)
);

CREATE TABLE QUARTO
(
    ID             INT
        CONSTRAINT PK_QUARTO PRIMARY KEY,
    ID_ANDAR       INT NOT NULL
        CONSTRAINT FK_QUARTO_ANDAR REFERENCES ANDAR (ID),
    NR_QUARTO      INT NOT NULL,
    ID_TIPO_QUARTO INT
        CONSTRAINT FK_QUARTO_TIPO_QUARTO REFERENCES TIPO_QUARTO (ID),
    LOTACAO_MAXIMA INT,
    CONSTRAINT UK_QUARTO UNIQUE (ID_ANDAR, NR_QUARTO)
);

CREATE TABLE RESERVA
(
    ID                 INT
        CONSTRAINT PK_RESERVA PRIMARY KEY,
    ID_CLIENTE         INT
        CONSTRAINT FK_RESERVA_CLIENTE REFERENCES CLIENTE (ID),
    NOME               VARCHAR(250),
    NIF                VARCHAR(20),
    EMAIL              VARCHAR(200),
    TELEFONE           VARCHAR(20),
    ID_TIPO_QUARTO     INT NOT NULL
        CONSTRAINT FK_RESERVA_TIPO_QUARTO REFERENCES TIPO_QUARTO (ID),
    DATA               DATE,
    DATA_ENTRADA       DATE,
    DATA_SAIDA         DATE,
    NR_PESSOAS         INT,
    PRECO              NUMBER(6, 2),
    ID_ESTADO_RESERVA  INT
        CONSTRAINT FK_RESERVA_ESTADO REFERENCES ESTADO_RESERVA (ID),
    CUSTO_CANCELAMENTO NUMBER(6, 2),
    CUSTO_EXTRA        NUMBER(6, 2)
);

CREATE TABLE CHECKIN
(
    ID_RESERVA INT
        CONSTRAINT PK_CHECKIN PRIMARY KEY
        CONSTRAINT FK_CHECKIN_ID_RESERVA REFERENCES RESERVA (ID),
    DATA       DATE NOT NULL,
    ID_QUARTO  INT
        CONSTRAINT FK_RESERVA_QUARTO REFERENCES QUARTO (ID)
);

CREATE TABLE HOSPEDES_CHECKIN
(
    ID_RESERVA              INT
        CONSTRAINT FK_HOSPEDES_CHECKIN_RESERVA REFERENCES CHECKIN (ID_RESERVA),
    NR_HOSPEDE              INT,
    CONSTRAINT PK_HOSPEDES_CHECKIN PRIMARY KEY (ID_RESERVA, NR_HOSPEDE),
    NOME                    VARCHAR(200),
    ID_PAIS
        CONSTRAINT FK_HOSPEDES_CHECKIN_PAIS REFERENCES PAIS (ID),
    GENERO                  VARCHAR(1)
        CONSTRAINT CK_HOSPEDES_CHECKIN_GENERO CHECK (UPPER(GENERO) IN ('M', 'F')),
    DOCUMENTO_IDENTIFICACAO VARCHAR(50)
);

CREATE TABLE CHECKOUT
(
    ID_RESERVA  INT
        CONSTRAINT PK_CHECKOUT_ID_RESERVA PRIMARY KEY
        CONSTRAINT FK_CHECKOUT_ID_RESERVA REFERENCES CHECKIN (ID_RESERVA),
    DATA        DATE NOT NULL,
    OBSERVACOES VARCHAR(1000),
    VALOR_EXTRA NUMBER(6, 2)
);

CREATE TABLE CONTA_CONSUMO
(
    ID            INT
        CONSTRAINT PK_CONTA_CONSUMO PRIMARY KEY,
    DATA_ABERTURA DATE,
    ID_RESERVA    INT
        CONSTRAINT FK_CONTA_CONSUMO_RESERVA REFERENCES RESERVA (ID)
);

CREATE TABLE ARTIGO_CONSUMO
(
    ID    INT
        CONSTRAINT PK_ARTIGO_CONSUMO PRIMARY KEY,
    NOME  VARCHAR(250),
    PRECO NUMBER(6, 2)
);

CREATE TABLE TIPO_FUNCIONARIO
(
    ID   INT
        CONSTRAINT PK_TIPO_FUNCIONARIO PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE FUNCIONARIO
(
    ID            INT
        CONSTRAINT PK_FUNCIONARIO PRIMARY KEY,
    NIF           VARCHAR(20),
    NOME          VARCHAR(250),
    MORADA        VARCHAR(200),
    CODIGO_POSTAL INT
        CONSTRAINT FK_FUNCIONARIO_CODIGO_POSTAL REFERENCES CODIGO_POSTAL (ID),
    EMAIL         VARCHAR(200),
    TELEFONE      VARCHAR(20),
    ID_TIPO_FUNCIONARIO
        CONSTRAINT FK_FUNCIONARIO_TIPO_FUNC REFERENCES TIPO_FUNCIONARIO (ID)
);

CREATE TABLE FUNCIONARIO_MANUTENCAO
(
    ID             INT
        CONSTRAINT PK_FUNCIONARIO_MANUTENCAO PRIMARY KEY
        CONSTRAINT FK_FUNCIONARIO_MANUTENCAO_FUNC REFERENCES FUNCIONARIO (ID),
    ID_RESPONSAVEL INT
        CONSTRAINT FK_FUNCIONARIO_MANUTENCAO_RESP REFERENCES FUNCIONARIO_MANUTENCAO (ID),
    TELEFONE       VARCHAR(20)
);

CREATE TABLE CAMAREIRA
(
    ID    INT
        CONSTRAINT PK_CAMAREIRA PRIMARY KEY
        CONSTRAINT FK_CAMAREIRA_FUNCIONARIO REFERENCES FUNCIONARIO (ID),
    BONUS NUMBER
);

CREATE TABLE LINHA_CONTA_CONSUMO
(
    ID_CONTA_CONSUMO  INT
        CONSTRAINT FK_LINHA_CONTA_CONSUMO REFERENCES CONTA_CONSUMO (ID),
    LINHA             INT,
    CONSTRAINT PK_LINHA_CONTA_CONSUMO PRIMARY KEY (ID_CONTA_CONSUMO, LINHA),
    ID_ARTIGO_CONSUMO INT
        CONSTRAINT FK_LINHA_CONTA_CONSUMO_ARTIGO REFERENCES ARTIGO_CONSUMO (ID),
    DATA_REGISTO      DATE,
    QUANTIDADE        INT,
    PRECO_UNITARIO    NUMBER(6, 2),
    ID_CAMAREIRA      INT
        CONSTRAINT FK_LINHA_CONTA_CONSUMO_CAM REFERENCES CAMAREIRA (ID)
);

CREATE TABLE FATURA
(
    ID                     INT
        CONSTRAINT PK_FATURA PRIMARY KEY,
    NUMERO                 INT
        CONSTRAINT NN_FATURA_NUMERO NOT NULL,
    DATA                   DATE NOT NULL,
    ID_CLIENTE             INT
        CONSTRAINT FK_FATURA_CLIENTE REFERENCES CLIENTE (ID),
    ID_RESERVA             INT UNIQUE
        CONSTRAINT FK_FATURA_RESERVA REFERENCES RESERVA (ID),
    VALOR_FATURADO_RESERVA NUMBER(8, 2),
    VALOR_FATURADO_CONSUMO NUMBER(8, 2)
);

CREATE TABLE LINHA_FATURA
(
    ID_FATURA           INT
        CONSTRAINT FK_LINHA_FATURA_FATURA REFERENCES FATURA (ID),
    LINHA               INT,
    CONSTRAINT PK_LINHA_FATURA PRIMARY KEY (ID_FATURA, LINHA),
    ID_CONTA_CONSUMO    INT,
    LINHA_CONTA_CONSUMO INT,
    CONSTRAINT FK_LINHA_FATURA_CONTA_CONSUMO FOREIGN KEY (ID_CONTA_CONSUMO, LINHA_CONTA_CONSUMO) REFERENCES LINHA_CONTA_CONSUMO (ID_CONTA_CONSUMO, LINHA),
    VALOR_CONSUMO       NUMBER(8, 2)
);

CREATE TABLE MODO_PAGAMENTO
(
    ID   INT
        CONSTRAINT PK_MODO_PAGAMENTO PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE PAGAMENTO
(
    ID_FATURA         INT
        CONSTRAINT FK_PAGAMENTO_FATURA REFERENCES FATURA (ID),
    ID_MODO_PAGAMENTO INT
        CONSTRAINT FK_PAGAMENTO_MODO REFERENCES MODO_PAGAMENTO (ID),
    VALOR             NUMBER(8, 2),
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (ID_FATURA, ID_MODO_PAGAMENTO)
);

CREATE TABLE TIPO_INTERVENCAO
(
    ID   INT
        CONSTRAINT PK_TIPO_INTERVENCAO PRIMARY KEY,
    NOME VARCHAR(250)
);

CREATE TABLE INTERVENCAO
(
    ID                  INT
        CONSTRAINT PK_INTERVENCAO PRIMARY KEY,
    ID_QUARTO           INT NOT NULL
        CONSTRAINT FK_INTERVENCAO REFERENCES QUARTO (ID),
    ID_FUNCIONARIO      INT
        CONSTRAINT FK_INTERVENCAO_FUNCIONARIO REFERENCES FUNCIONARIO (ID),
    DATA                DATE,
    DESCRICAO           VARCHAR(1000),
    ID_TIPO_INTERVENCAO INT NOT NULL
        CONSTRAINT FK_INTERVENCAO_TIPO REFERENCES TIPO_INTERVENCAO (ID)
);
