CREATE TRIGGER TRGATUALIZACLIENTE
    BEFORE INSERT OR UPDATE
    ON RESERVA
    FOR EACH ROW
DECLARE
    AUX_NOMECLIENTE VARCHAR2(250);
    AUX_NIF         NUMBER;
    AUX_EMAIL       VARCHAR2(250);
    AUX_TELEFONE    NUMBER;
    FLAG            NUMBER;
BEGIN

    IF :NEW.ID_CLIENTE IS NOT NULL THEN
        -- VAMOS VERIFICAR SE O CLIENTE COM O :NEW.ID_CLIENTE EXISTE
        FLAG := 0;
        SELECT C.ID
        INTO FLAG
        FROM CLIENTE C
        WHERE C.ID = :NEW.ID_CLIENTE;

        -- VAMOS SELECIONAR OS DADOS DO CLIENTE PARA AS VARIAVEIS AUXILIARES PARA GUARDAR NA RESERVA
        SELECT C.NOME, C.NIF, C.EMAIL, C.TELEFONE
        INTO AUX_NOMECLIENTE, AUX_NIF, AUX_EMAIL, AUX_TELEFONE
        FROM CLIENTE C
        WHERE C.ID = :NEW.ID_CLIENTE;

        -- A INSERIR VAMOS FAZER UPDATE AOS DADOS QUE NAO SAO INSERIDOS (APENAS SE COLOCA O ID)
        -- AO FAZER UPDATE VAMOS ATUALIZAR OS DADOS PRESENTES NA RESERVA
        IF INSERTING THEN
            :NEW.NOME := AUX_NOMECLIENTE;
            :NEW.NIF := AUX_NIF;
            :NEW.EMAIL := AUX_EMAIL;
            :NEW.TELEFONE := AUX_TELEFONE;
        ELSIF UPDATING THEN
            :NEW.NOME := AUX_NOMECLIENTE;
            :NEW.NIF := AUX_NIF;
            :NEW.EMAIL := AUX_EMAIL;
            :NEW.TELEFONE := AUX_TELEFONE;
        END IF;
    END IF;
END;

-- TEST
BEGIN
    INSERT INTO CLIENTE VALUES (501, 'CLIENTE 501 TESTE', 1234, 1, 'EMAIL123@ABC.PT', 1234567);
    -- ATUALIZA OS DADOS DA RESERVA Nº207 COM OS DADOS DO CLIENTE 86
    UPDATE RESERVA
    SET ID_CLIENTE = 501
    WHERE ID = 3653;

    -- VAI CRIAR A RESERVA COM O ID 9999 COM TODOS OS DADOS DO CLIENTE 86 APESAR DE COLOCAR NULL EM TODOS
    INSERT INTO RESERVA
    VALUES (9999, 501, NULL, NULL, NULL, NULL, 1, SYSDATE, SYSDATE + 1, SYSDATE + 2, 1, 0, 1, 0, 0);
END;
