-- PARA QUE FUNCIONE:
-- 1. USAR [EXECUTE IMMEDIATE 'ALTER TABLE CAMAREIRA ADD (BONUS NUMBER)';]
-- 2. ADICIONAR A TABELA CAMAREIRA A COLUNA BONUS
-- O CASO 1 APENAS FUNCIONA 1X, IRA DAR ERRO DE TODAS AS VEZES QUE SE CORRA DEPOIS DA PRIMEIRA VEZ
CREATE OR REPLACE PROCEDURE PRCATUALIZARBONUSCAMAREIRAS(P_MES NUMBER, P_ANO NUMBER) IS
    CONSUMOS_ID_CURSOR    SYS_REFCURSOR;
    ID_CAMAREIRA_ADDBONUS NUMBER;
    CONSUMO_CAMAREIRA     NUMBER;
    AUX_ANO               NUMBER;
BEGIN

    --VERIFICACAO PARA O ANO, CASO SEJA NULL TEM DE SER O ATUAL
    IF P_ANO IS NULL OR P_ANO = 0 THEN
        AUX_ANO := EXTRACT(YEAR FROM SYSDATE);
    ELSIF P_ANO IS NOT NULL THEN
        AUX_ANO := P_ANO;
    END IF;


    -- ABRE O CURSOR CRIADO PARA GUARDAR A INFO DO CONSUMO REGISTADOS E O ID DA CAMAREIRA ASSOCIADO A ESSE VALOR,
    -- FILTRANDO A TABELA LINHA_CONTA_CONSUMO ATRAVES DO ANO/MES PRETENDIDOS
    OPEN CONSUMOS_ID_CURSOR FOR
        SELECT SUM(LCC.QUANTIDADE * LCC.PRECO_UNITARIO) AS CONSUMO, LCC.ID_CAMAREIRA
        FROM LINHA_CONTA_CONSUMO LCC
        WHERE EXTRACT(YEAR FROM LCC.DATA_REGISTO) = P_ANO
          AND EXTRACT(MONTH FROM LCC.DATA_REGISTO) = P_MES
        GROUP BY LCC.ID_CAMAREIRA;

    -- ESTE LOOP TEM UM OUTPUT PARA MOSTRAR O ID DA CAMAREIRA E O VALOR E O SEU BONUS. USA UMA CADEIA DE IFS PARA
    -- PREENCHER A TABELA COM OS BONUS PRETENDIDOS
    LOOP
        FETCH CONSUMOS_ID_CURSOR INTO
            CONSUMO_CAMAREIRA, ID_CAMAREIRA_ADDBONUS;

        IF CONSUMO_CAMAREIRA > 1000 THEN
            UPDATE CAMAREIRA SET BONUS = CONSUMO_CAMAREIRA * 0.15 WHERE ID = ID_CAMAREIRA_ADDBONUS;
            DBMS_OUTPUT.PUT_LINE(
                        'ID: ' || ID_CAMAREIRA_ADDBONUS || ' | REGISTO: ' || CONSUMO_CAMAREIRA || ' EUR | BONUS: ' ||
                        CONSUMO_CAMAREIRA * 0.15 || ' EUR');
        ELSIF CONSUMO_CAMAREIRA BETWEEN 500 AND 1000 THEN
            UPDATE CAMAREIRA SET BONUS = CONSUMO_CAMAREIRA * 0.10 WHERE ID = ID_CAMAREIRA_ADDBONUS;
            DBMS_OUTPUT.PUT_LINE(
                        'ID: ' || ID_CAMAREIRA_ADDBONUS || ' | REGISTO: ' || CONSUMO_CAMAREIRA || ' EUR | BONUS: ' ||
                        CONSUMO_CAMAREIRA * 0.10 || ' EUR');
        ELSIF CONSUMO_CAMAREIRA BETWEEN 100 AND 500 THEN
            UPDATE CAMAREIRA SET BONUS = CONSUMO_CAMAREIRA * 0.05 WHERE ID = ID_CAMAREIRA_ADDBONUS;
            DBMS_OUTPUT.PUT_LINE(
                        'ID: ' || ID_CAMAREIRA_ADDBONUS || ' | REGISTO: ' || CONSUMO_CAMAREIRA || ' EUR | BONUS: ' ||
                        CONSUMO_CAMAREIRA * 0.05 || ' EUR');
        ELSE
            UPDATE CAMAREIRA SET BONUS = 0 WHERE ID = ID_CAMAREIRA_ADDBONUS;
            DBMS_OUTPUT.PUT_LINE(
                        'ID: ' || ID_CAMAREIRA_ADDBONUS || ' | REGISTO: ' || CONSUMO_CAMAREIRA || ' EUR | BONUS: ' ||
                        0 || ' EUR');
        END IF;

        EXIT WHEN CONSUMOS_ID_CURSOR%NOTFOUND;

    END LOOP;
END;

-- TEST
BEGIN
    DBMS_OUTPUT.PUT_LINE('MES 10 2020');
    PRCATUALIZARBONUSCAMAREIRAS(10, 2020);
    DBMS_OUTPUT.PUT_LINE('MES 12 2020');
    PRCATUALIZARBONUSCAMAREIRAS(2, 2020);
END;

