-- ASSUME QUE AS LINHAS DE FATURA E DE CONSUMO SEJAM PREVIAMENTE INTRODUZIDAS EM SISTEMA, VISTO QUE SEMPRE QUE É
-- EFETUADO UM CONSUMO É GERADA UMA LINHA DE CONSUMO E ESSA CONTA CONSUMO VAI CONSTAR NAS LINHAS DE CADA FATURA DE
-- CADA CLIENTE. PARA QUE ESTE PROCEDURE FUNCIONE E CONTE COM AS CONDIÇÕES MENCIONADAS TIVEMOS DE ADICIONAR INSERTS
-- PARA A TABELA LINHA_CONSUMO
CREATE OR REPLACE PROCEDURE PRCCHECKOUT(LINHA_RESERVA IN RESERVA%ROWTYPE)
AS
    LINHA_INVALIDA EXCEPTION;
    C_DADOSFATURAR        SYS_REFCURSOR;
    CONSUMO_TOTAL         NUMBER;
    VALOR_ESTADIA         NUMBER;
    AUX_NUMFATURA         NUMBER;
    AUX_IDFATURA          NUMBER;
    AUX_CONTADOR_LINHAFAT NUMBER;
    AUX_IDCC              NUMBER;
    AUX_VALORCONSUMO      NUMBER;
    AUX_LCC               NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================================================');
    DBMS_OUTPUT.PUT_LINE('RESERVA COM O ID: ' || LINHA_RESERVA.ID);

    -- VAMOS OBTER E CALCULAR O ID E NUM DA FATURA A GERAR
    SELECT MAX(F.ID), MAX(F.NUMERO)
    INTO AUX_IDFATURA, AUX_NUMFATURA
    FROM FATURA F;
    IF (AUX_IDFATURA IS NULL AND AUX_NUMFATURA IS NULL) THEN
        AUX_IDFATURA := 0;
        AUX_NUMFATURA := 0;
    END IF;
    DBMS_OUTPUT.PUT_LINE('ID: ' || AUX_IDFATURA);
    DBMS_OUTPUT.PUT_LINE('NUM: ' || AUX_NUMFATURA);
    AUX_IDFATURA := AUX_IDFATURA + 1;
    AUX_NUMFATURA := AUX_NUMFATURA + 1;
    DBMS_OUTPUT.PUT_LINE('A GERAR FATURA NUM: ' || AUX_NUMFATURA);

    DBMS_OUTPUT.PUT_LINE('Antes do OBTER ID DA CONTA CC');
    -- VAMOS OBTER O ID DA CONTA CONSUMO ASSOCIADO A ESTA RESERVA
    SELECT CC.ID
    INTO AUX_IDCC
    FROM CONTA_CONSUMO CC
    WHERE CC.ID_RESERVA = LINHA_RESERVA.ID;
    DBMS_OUTPUT.PUT_LINE('CONTA CONSUMO ASSOCIADA: ' || AUX_IDCC);

    -- COLOCA EM CONSUMO_TOTAL O VALOR TOTAL DE TODOS OS CONSUMOS EFETUADOS
    SELECT SUM(LCC.QUANTIDADE * LCC.PRECO_UNITARIO)
    INTO CONSUMO_TOTAL
    FROM LINHA_CONTA_CONSUMO LCC
             JOIN CONTA_CONSUMO CC ON CC.ID = LCC.ID_CONTA_CONSUMO
    WHERE CC.ID_RESERVA = LINHA_RESERVA.ID;
    DBMS_OUTPUT.PUT_LINE('VALOR TOTAL DOS CONSUMOS: ' || CONSUMO_TOTAL);

    -- CALCULA O VALOR TOTAL A PAGAR PELA ESTADIA TENDO EM CONTA A ÉPOCA DO ANO EM QUE A RESERVA FOI FEITA, USANDO
    -- UMA INNER QUERY (SELECT DENTRO DE SELECT)
    SELECT PCTQ.PRECO * (TRUNC(LINHA_RESERVA.DATA_SAIDA) - TRUNC(LINHA_RESERVA.DATA_SAIDA))
    INTO VALOR_ESTADIA
    FROM PRECO_EPOCA_TIPO_QUARTO PCTQ
    WHERE PCTQ.ID_TIPO_QUARTO = LINHA_RESERVA.ID_TIPO_QUARTO
      AND PCTQ.ID_EPOCA = (SELECT E.ID
                           FROM EPOCA E
                           WHERE (LINHA_RESERVA.DATA_ENTRADA) BETWEEN E.DATA_INI AND E.DATA_FIM
    );

    -- CRIAMOS A FATURA EM BRANCO PARA POSTERIORMENTE GERAR AS LINHAS DA FATURA
    INSERT INTO FATURA
    VALUES (AUX_IDFATURA, AUX_NUMFATURA, SYSDATE, LINHA_RESERVA.ID_CLIENTE, LINHA_RESERVA.ID, VALOR_ESTADIA,
            CONSUMO_TOTAL);

    -- VAMOS COLOCAR NO CURSOS C_DADOSFATURAR A LINHA DA CONTA CONSUMO E O VALOR ASSOCIADO A ESSA LINHA PARA COLOCAR
    -- NA FATURA
    OPEN C_DADOSFATURAR FOR
        SELECT LCC2.LINHA, (LCC2.QUANTIDADE * LCC2.PRECO_UNITARIO) AS CONSUMO
        FROM LINHA_CONTA_CONSUMO LCC2
        WHERE LCC2.ID_CONTA_CONSUMO = AUX_IDCC;

    -- INICIAR O CONTADOR DE LINHAS DA FATURA A 0
    AUX_CONTADOR_LINHAFAT := 0;

    -- VAMOS CRIAR AS LINHAS DA FATURA COM OS VALORES ID_FATURA, LINHA_FATURA, ID_CONTACONSUMO, LINHA_CONTACONSUMO,
    -- VALORCONSUMO
    DBMS_OUTPUT.PUT_LINE('A GERAR AS LINHAS DA FATURA...');
    LOOP
        FETCH C_DADOSFATURAR INTO AUX_LCC, AUX_VALORCONSUMO;
        EXIT WHEN C_DADOSFATURAR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('LINHA DA CONTA CONSUMO: ' || AUX_LCC || ' | VALOR: ' || AUX_VALORCONSUMO);
        INSERT INTO LINHA_FATURA VALUES (AUX_IDFATURA, AUX_CONTADOR_LINHAFAT, AUX_IDCC, AUX_LCC, AUX_VALORCONSUMO);
        AUX_CONTADOR_LINHAFAT := AUX_CONTADOR_LINHAFAT + 1;
    END LOOP;

    -- CRIA O CHECKOUT DO QUARTO/RESERVA
    INSERT INTO CHECKOUT
    VALUES (LINHA_RESERVA.ID, LINHA_RESERVA.DATA_SAIDA, '', 0);
    DBMS_OUTPUT.PUT_LINE('CHECKOUT GERADO!');
    DBMS_OUTPUT.PUT_LINE('========================================================================');
END;

COMMIT;

DECLARE
    LINHA RESERVA%ROWTYPE;
BEGIN
    SELECT * INTO LINHA FROM RESERVA R WHERE R.ID = 3651;
    PRCCHECKOUT(LINHA);
    SELECT * INTO LINHA FROM RESERVA R WHERE R.ID = 3652;
    PRCCHECKOUT(LINHA);
    SELECT * INTO LINHA FROM RESERVA R WHERE R.ID = 3653;
    PRCCHECKOUT(LINHA);
END;